"""
GOLD REAPER :: first-run setup wizard
=====================================
Runs once after install (and any time you re-run it). Asks a handful of
questions, writes .env, tests the broker connection, prints a checklist.

Interactive:
    python -m setup.wizard

Headless (installers / CI / docker):
    python -m setup.wizard --non-interactive --broker paper
    python -m setup.wizard --non-interactive --broker paper \\
        --risk 1.0 --session-target 20 --daily-target 120 --daily-loss 3

Brokers: paper (default, safe) | exness (MT5, Windows) | bitget (ccxt)
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

_TTY = sys.stdout.isatty()
GREEN = "\033[32m" if _TTY else ""
RED = "\033[31m" if _TTY else ""
YEL = "\033[33m" if _TTY else ""
DIM = "\033[90m" if _TTY else ""
NC = "\033[0m" if _TTY else ""

# Windows terminals: force UTF-8 so the box drawing never explodes cp1252
if os.name == "nt":
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
        sys.stdin.reconfigure(encoding="utf-8")   # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001
        pass

ENV_PATH = ROOT / ".env"

# keys the wizard OWNS (everything else in an existing .env is preserved)
MANAGED = [
    "BROKER", "PAPER_MODE",
    "MT5_LOGIN", "MT5_PASSWORD", "MT5_SERVER", "MT5_SYMBOL",
    "BITGET_KEY", "BITGET_SECRET", "BITGET_PASSPHRASE", "BITGET_SYMBOL",
    "BITGET_LEVERAGE",
    "STARTING_BALANCE", "RISK_PER_TRADE_PCT", "MAX_DAILY_LOSS_PCT",
    "TARGET_PER_SESSION_USD", "TARGET_PER_DAY_USD", "STOP_AFTER_TARGET",
    "TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID",
]


def _ask(prompt: str, default: str, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        if secret:
            import getpass
            val = getpass.getpass(f"{prompt}{suffix}: ")
        else:
            val = input(f"{prompt}{suffix}: ")
    except (EOFError, KeyboardInterrupt):
        print()
        raise SystemExit(130)
    return val.strip() or default


def _ask_float(prompt: str, default: float) -> float:
    while True:
        raw = _ask(prompt, f"{default:g}")
        try:
            return float(raw)
        except ValueError:
            print(f"  {RED}[!]{NC} enter a number, e.g. 1.0")


def _ask_int(prompt: str, default: int) -> int:
    while True:
        raw = _ask(prompt, str(default))
        try:
            return int(raw)
        except ValueError:
            print(f"  {RED}[!]{NC} enter a whole number, e.g. 20")


def _merge_env(new: dict[str, str]) -> None:
    """Update MANAGED keys in place; preserve every other line/key."""
    existing: dict[str, str] = {}
    lines: list[str] = []
    if ENV_PATH.exists():
        for raw in ENV_PATH.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if stripped and not stripped.startswith("#") and "=" in stripped:
                k, _, v = stripped.partition("=")
                existing[k.strip()] = v
            lines.append(raw)
    existing.update(new)

    if lines:
        seen: set[str] = set()
        out: list[str] = []
        for raw in lines:
            stripped = raw.strip()
            if stripped and not stripped.startswith("#") and "=" in stripped:
                k = stripped.partition("=")[0].strip()
                if k in MANAGED and k in seen:
                    continue                      # drop duplicated managed keys
                if k in MANAGED:
                    seen.add(k)
                    out.append(f"{k}={existing[k]}")
                else:
                    out.append(raw)
            else:
                out.append(raw)
        for k in MANAGED:                          # append keys not present yet
            if k not in seen and k in existing:
                out.append(f"{k}={existing[k]}")
        ENV_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    else:
        body = "\n".join(f"{k}={existing.get(k, '')}" for k in MANAGED)
        ENV_PATH.write_text(
            "# GOLD REAPER :: generated by setup wizard\n"
            "# NEVER commit this file\n\n" + body + "\n", encoding="utf-8")


def _test_broker(choice: str, creds: dict[str, str]) -> tuple[bool, str]:
    """Returns (ok, human message). Never raises."""
    if choice == "PAPER":
        return True, "virtual exchange armed (no account needed)"
    try:
        from core.config import Config

        cfg = Config()
        for k, v in creds.items():
            setattr(cfg, k, v)
        cfg.broker = choice
        cfg.paper = False
        if choice == "MT5":
            from brokers.mt5_broker import ExnessMT5
            b = ExnessMT5(cfg)
            ok = b.connect()
            try:
                b.disconnect()
            except Exception:  # noqa: BLE001
                pass
            if ok:
                return True, f"MT5 terminal reachable, symbol {cfg.mt5_symbol} verified"
            return False, ("MT5 terminal not reachable. On Windows install "
                           "MetaTrader 5 (Exness) and allow automated trading. "
                           "See docs/TROUBLESHOOTING.md #4")
        if choice == "BITGET":
            from brokers.bitget_broker import BitgetBroker
            b = BitgetBroker(cfg)
            ok = b.connect()
            if ok:
                return True, f"Bitget reachable, market {b.symbol}"
            return False, ("Bitget connection failed. Check keys / IP whitelist. "
                           "See docs/TROUBLESHOOTING.md #5")
    except Exception as e:  # noqa: BLE001
        return False, f"broker test error: {e}"
    return False, "unknown broker"


def interactive() -> dict[str, str]:
    print(f"""
{GREEN}+--------------------------------------------------------+
|  GOLD REAPER :: first-time setup                        |
|  autonomous XAU/USD hunter · cross-platform             |
+--------------------------------------------------------+{NC}

  1. Choose broker
     [1] {YEL}Paper{NC}  (safe, virtual balance, no account)  <- default
     [2] {YEL}Exness{NC} (MetaTrader 5, real XAUUSD, Windows)
     [3] {YEL}Bitget{NC} (XAUT/USDT tokenized-gold futures)
""")
    c = _ask("  broker", "1")
    choice = {"1": "PAPER", "2": "MT5", "3": "BITGET"}.get(c.strip("[]123 "), "PAPER")
    creds: dict[str, str] = {}

    if choice == "PAPER":
        print(f"\n  {DIM}paper mode: virtual balance, real market data,"
              f" zero risk.{NC}")
    elif choice == "MT5":
        print(f"\n  {DIM}find login/server in your Exness MT5 terminal:"
              f" Tools -> Options, or in the account email.{NC}")
        creds["mt5_login"] = str(_ask_int("  2a. MT5 login (account number)", 0))
        creds["mt5_password"] = _ask("  2b. MT5 password", "", secret=True)
        creds["mt5_server"] = _ask("  2c. MT5 server", "Exness-MT5Trial")
        creds["mt5_symbol"] = _ask("  2d. gold symbol", "XAUUSD")
    elif choice == "BITGET":
        print(f"\n  {DIM}create an API key at bitget.com -> API keys;"
              f" enable Futures trade; IP-whitelist strongly advised.{NC}")
        creds["bitget_key"] = _ask("  2a. API key", "")
        creds["bitget_secret"] = _ask("  2b. API secret", "", secret=True)
        creds["bitget_passphrase"] = _ask("  2c. API passphrase", "", secret=True)

    risk = _ask_float("  3. Risk per trade %", 1.0)
    while not (0.05 <= risk <= 2.0):
        print(f"  {RED}[!]{NC} safety rails: risk must be 0.05..2.0 %"
              f" (docs/RISK.md). Try again.")
        risk = _ask_float("  3. Risk per trade %", 1.0)
    session_target = _ask_float("  4. Session target USD (per 4h block)", 20.0)
    daily_target = _ask_float("  5. Daily target USD", 120.0)
    daily_loss = abs(_ask_float("  6. Daily loss stop %", 3.0))

    tg = _ask("  7. Telegram alerts? token (empty = skip)", "")
    tg_chat = ""
    if tg:
        tg_chat = _ask("      telegram chat id", "")

    print()
    ok, msg = _test_broker(choice, creds)
    mark = f"{GREEN}[OK]{NC}" if ok else f"{RED}[!]{NC}"
    print(f"  {mark} broker test: {msg}")
    if not ok and choice != "PAPER":
        fb = _ask("      fall back to PAPER while you fix this? [Y/n]", "Y")
        if fb.strip().lower() != "n":
            choice = "PAPER"
            creds = {}
            print(f"  {GREEN}[OK]{NC} will start in PAPER mode")

    return {
        "BROKER": choice,
        "PAPER_MODE": "true" if choice == "PAPER" else "false",
        "MT5_LOGIN": creds.get("mt5_login", ""),
        "MT5_PASSWORD": creds.get("mt5_password", ""),
        "MT5_SERVER": creds.get("mt5_server", "Exness-MT5Trial"),
        "MT5_SYMBOL": creds.get("mt5_symbol", "XAUUSD"),
        "BITGET_KEY": creds.get("bitget_key", ""),
        "BITGET_SECRET": creds.get("bitget_secret", ""),
        "BITGET_PASSPHRASE": creds.get("bitget_passphrase", ""),
        "BITGET_SYMBOL": "XAUT/USDT:USDT",
        "BITGET_LEVERAGE": "3",
        "STARTING_BALANCE": "1000",
        "RISK_PER_TRADE_PCT": f"{risk:g}",
        "MAX_DAILY_LOSS_PCT": f"{daily_loss:g}",
        "TARGET_PER_SESSION_USD": f"{session_target:g}",
        "TARGET_PER_DAY_USD": f"{daily_target:g}",
        "STOP_AFTER_TARGET": "true",
        "TELEGRAM_BOT_TOKEN": tg,
        "TELEGRAM_CHAT_ID": tg_chat,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="GOLD REAPER first-time setup")
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--broker", default="paper",
                    choices=["paper", "exness", "mt5", "bitget"])
    ap.add_argument("--risk", type=float, default=1.0)
    ap.add_argument("--session-target", type=float, default=20.0)
    ap.add_argument("--daily-target", type=float, default=120.0)
    ap.add_argument("--daily-loss", type=float, default=3.0)
    ap.add_argument("--starting-balance", type=float, default=1000.0)
    ap.add_argument("--telegram-token", default="")
    ap.add_argument("--telegram-chat", default="")
    ap.add_argument("--mt5-login", default="")
    ap.add_argument("--mt5-password", default="")
    ap.add_argument("--mt5-server", default="Exness-MT5Trial")
    ap.add_argument("--bitget-key", default="")
    ap.add_argument("--bitget-secret", default="")
    ap.add_argument("--bitget-passphrase", default="")
    args = ap.parse_args()

    if args.non_interactive:
        broker = {"PAPER": "PAPER", "EXNESS": "MT5", "MT5": "MT5",
                  "BITGET": "BITGET"}[args.broker.upper()]
        risk = min(2.0, max(0.05, args.risk))
        env = {
            "BROKER": broker,
            "PAPER_MODE": "true" if broker == "PAPER" else "false",
            "MT5_LOGIN": args.mt5_login,
            "MT5_PASSWORD": args.mt5_password,
            "MT5_SERVER": args.mt5_server,
            "MT5_SYMBOL": "XAUUSD",
            "BITGET_KEY": args.bitget_key,
            "BITGET_SECRET": args.bitget_secret,
            "BITGET_PASSPHRASE": args.bitget_passphrase,
            "BITGET_SYMBOL": "XAUT/USDT:USDT",
            "BITGET_LEVERAGE": "3",
            "STARTING_BALANCE": f"{args.starting_balance:g}",
            "RISK_PER_TRADE_PCT": f"{risk:g}",
            "MAX_DAILY_LOSS_PCT": f"{abs(args.daily_loss):g}",
            "TARGET_PER_SESSION_USD": f"{args.session_target:g}",
            "TARGET_PER_DAY_USD": f"{args.daily_target:g}",
            "STOP_AFTER_TARGET": "true",
            "TELEGRAM_BOT_TOKEN": args.telegram_token,
            "TELEGRAM_CHAT_ID": args.telegram_chat,
        }
        tested, msg = _test_broker(broker, {})
        mark = f"{GREEN}[OK]{NC}" if tested else f"{RED}[!]{NC}"
        print(f"  {mark} broker test: {msg}")
    else:
        env = interactive()

    _merge_env(env)
    print(f"\n  {GREEN}[OK]{NC} wrote .env        ({ENV_PATH})")
    print(f"  {GREEN}[OK]{NC} tested broker")
    print(f"  {GREEN}[OK]{NC} ready to hunt")
    print(f"""
  start it:
    {'start_windows.bat' if os.name == 'nt' else './start.sh'}
  manage later:
    python -m setup.wizard        # re-run this wizard
    python bot.py --reset-breakers
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
